---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-csi-node-binding
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: efs-csi-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: efs-csi-node
  apiGroup: rbac.authorization.k8s.io
