apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: efs-csi-node
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
{{- if not .Values.global.podSecurityStandards.enforced }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - efs-csi-node
  verbs:
  - use
{{- end }}
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
