apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: efs-csi-controller
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - efs-csi-controller
  verbs:
  - use
