{{- if .Values.controller.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-csi-provisioner-binding
  labels:
    app.kubernetes.io/name: {{ include "aws-efs-csi-driver.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-efs-csi-driver.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: efs-csi-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}