{{- if .Values.controller.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aws-efs-csi-controller
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name | quote }}
  policyTypes:
  - Egress
{{- end }}
