{{- if .Values.global.podSecurityStandards.enforced }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: efs-csi-node-exceptions
  namespace: giantswarm 
spec:
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
        - autogen-require-drop-all
    - policyName: disallow-host-path
      ruleNames:
        - autogen-host-path
        - host-path
    - policyName: restrict-volume-types
      ruleNames:
        - autogen-restricted-volumes
        - restricted-volumes
    - policyName: require-run-as-nonroot
      ruleNames:
        - autogen-run-as-non-root
        - run-as-nonroot
    - policyName: restrict-seccomp-strict
      ruleNames:
        - autogen-check-seccomp-strict
        - check-seccomp-strict 
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
        - autogen-privilege-escalation 
    - policyName: disallow-privileged-containers
      ruleNames:
        - autogen-privileged-containers 
        - privileged-containers
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - {{ .Release.Namespace }}
          names:
            - efs-csi-node*
{{- end }}
