{{- if .Values.global.podSecurityStandards.enforced }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: efs-csi-node-exceptions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
        - autogen-require-drop-all
    - policyName: disallow-host-path
      ruleNames:
        - autogen-host-path
    - policyName: restrict-volume-types
      ruleNames:
        - autogen-restricted-volumes
    - policyName: require-run-as-nonroot
      ruleNames:
        - autogen-run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - autogen-check-seccomp-strict
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privileged-containers
        - autogen-privileged-containers
    - policyName: disallow-privileged-containers
      ruleNames:
        - privilege-escalation
        - autogen-privilege-escalation
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          namespaces:
            - {{ .Release.Namespace }}
          names:
            - efs-csi-node*
{{- end }}
