{{- if .Values.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-efs-csi-driver.serviceAccountName" . }}
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ include "aws-efs-csi-driver.name" . }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}